name: Run Hello.py from Repo
on: push

jobs:
    run_hello:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: listing the dir
          run: |
            ls -ls
            chmod 777 hello.py 

        - name: Run python file
          run: python hello.py